#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

#
# CHPL_MAKE_THREADS stuff
#
#
#
CHPL_MAKE_THREADS      := $(shell $(CHPL_MAKE_HOME)/util/chplenv/threads)
CHPL_MAKE_THREADS_UBAR := $(subst -,_,$(CHPL_MAKE_THREADS))
