#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

#
# CHPL_MAKE_TASKS stuff
#
#
#
CHPL_MAKE_TASKS      := $(shell $(CHPL_MAKE_HOME)/util/chplenv/tasks)
CHPL_MAKE_TASKS_UBAR := $(subst -,_,$(CHPL_MAKE_TASKS))
