#
# Copyright (c) 2004-2013, Cray Inc.  (See LICENSE file for more details)
#

#
# CHPL_MAKE_ATOMICS
#
#
#
CHPL_MAKE_ATOMICS = $(shell $(CHPL_MAKE_HOME)/util/chplenv/atomics $(CHPL_MAKE_HOST_TARGET))
